% postprocess_barenblatt_errors.m
%
% Postprocess errors for data generated by run_barenblatt_configurable.m.
%
% Main features:
%   1. Read all_case_results.mat generated by run_barenblatt_configurable.m.
%      If all_case_results.mat is not found, recursively read case_result.mat.
%   2. If G(p)=0, the time-history and spatial summaries may use the exact
%      time-shifted Barenblatt solution as reference.
%   3. Temporal convergence has its own reference mode.  By default it uses
%      the smallest-tau numerical solution on the same N, so spatial errors
%      are largely cancelled in the temporal convergence plot.
%   4. Plot L1 and Linf errors as functions of time.
%   5. Reduce time-dependent errors to a scalar by one of three choices:
%        'at_time'    : error at one selected time;
%        'mean_after' : average error over saved times t > startTime;
%        'max_after'  : maximum error over saved times t > startTime.
%
% This script does not modify the original numerical data.  It only writes
% postprocessing files into a subfolder under rootDir.

clear; clc; close all;

%% ===================== User settings =====================

% Folder produced by run_barenblatt_configurable.m.
rootDir = 'barenblatt_configurable_data';

% Leave empty to process all detected groups.  Examples:
%   GTagList = {'G0'};
%   GTagList = {'G1mp'};
GTagList = {};

% Leave empty to process all detected gamma values.  Examples: [3], [20].
gammaList = [];

% Leave empty to process all detected C values.
CList = [];

% Leave empty to process all N values.  Example:
%   NList = [4, 8, 16, 32, 128, 512];
NList = [4096];

% Leave empty to process all tau values.  Example:
%   tauList = [1e-3, 5e-4, 2.5e-4];
tauList = 0.1*[1, 1/2, 1/4, 1/8, 1/16, 1/32, 1/64,1/512];

% Data source:
%   'auto'             : use all_case_results.mat when available; if NList or
%                        tauList is set, also scan case_result.mat so older
%                        manually selected runs are not hidden by a newer
%                        group summary file.
%   'all_case_results' : only read all_case_results.mat.
%   'case_result'      : only read case_result.mat files.
dataReadMode = 'auto';

% Interpolation method for numerical reference in space.
interpMethod = 'linear';

% Interpolation method for numerical reference in time when saved output
% times do not coincide exactly.  Usually this is not needed because the
% driver uses common outputTimes, but it makes the postprocessor robust.
timeInterpMethod = 'linear';

% How to reduce error(t) to one scalar error in the summary table.
% Options: 'at_time', 'mean_after', 'max_after'.
% The default matches max_{t > 0.05} h * sum_i |n_i(t) - n_ref(x_i,t)|.
scalarErrorMode = 'max_after';

% Used when scalarErrorMode = 'at_time'.  If empty, use the final saved time
% of each run.
targetTime = [];

% Used when scalarErrorMode = 'mean_after' or 'max_after'.
startTime = 0.1;

% Reference mode for temporal convergence.
%   'exact'            : use exact Barenblatt solution when available.
%   'numerical_same_N' : use the smallest-tau solution on the same N as reference.
temporalReferenceMode = 'exact';

% Whether to omit the numerical reference run itself from summary tables.
omitReferenceFromSummary = true;

% Plot options.
makePlots = true;
showTimeHistoryPlots = false;
showGridErrorPlots = true;
showGridReferenceLine = true;
gridReferenceSlope = 1;
plotLinf = true;
plotReferenceZeroCurve = false;

% Grid-error plot style.
gridPlotFigurePosition = [120, 120, 720, 560];
gridPlotLineWidth = 2.9;
gridPlotMarkerSize = 10;
gridPlotColors = [ ...
    0.0000, 0.4470, 0.7410; ...  % blue
    0.8500, 0.1000, 0.1000; ...  % red
    0.9290, 0.6940, 0.1250; ...  % yellow
    0.4700, 0.6700, 0.1900  ...  % green
    ];
gridPlotLineStyles = {'-', '--', '-.', ':'};
gridPlotMarkers = {'o', 's', '^', 'd', 'v', '>', '<', 'p', 'h', 'x'};
gridPlotReferenceLineWidth = 2.5;
gridPlotReferenceAnchor = 'min';
gridPlotReferenceScale = 15;
gridPlotReferenceTrimLeftFraction = 0.04;
gridPlotReferenceTrimRightFraction = 0.28;
gridPlotTitleText = 'Temporal convergence error';
gridPlotXLabelText = '$\tau$';
gridPlotYLabelText = '$\mathcal{E}_{h,\tau}$';
gridPlotTitleFontSize = 27;
gridPlotAxisLabelFontSize = 27;
gridPlotTickFontSize = 27;
gridPlotAxesLineWidth = 1.5;
gridPlotLegendFontSize = 22;
gridPlotLegendLocation = 'southeast';
gridPlotReferenceStyle = 'k--';
gridPlotXScale = 'log';
gridPlotYScale = 'log';

% Axis limits and ticks.  Leave [] or {} for automatic settings.
% Examples:
%   gridPlotXLim = [1e-4, 1e-2];
%   gridPlotYLim = [1e-4, 2e-1];
%   gridPlotXTicks = [1e-4, 1e-3, 1e-2];
%   gridPlotYTicks = [1e-4, 1e-3, 1e-2, 1e-1];
% gridPlotXLim = [1e-5, 1.3e-3];
% gridPlotYLim = [2e-7, 3e-3];
% gridPlotXTicks = [1e-7, 1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 1e-1];
% gridPlotYTicks = [1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 1e-1];
gridPlotXLim = [];
gridPlotYLim = [];
gridPlotXTicks = [1e-7, 1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 1e-1];
gridPlotYTicks = [1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 1e-1];
gridPlotXTickLabels = {};
gridPlotYTickLabels = {};
gridPlotAutoFormatXTicks = true;
gridPlotUseDataXTicks = true;
gridPlotTickDir = 'in';
gridPlotTickLength = [0.01, 0.01];
gridPlotSaveFig = true;

gridPlotOptions = struct();
gridPlotOptions.figurePosition = gridPlotFigurePosition;
gridPlotOptions.lineWidth = gridPlotLineWidth;
gridPlotOptions.markerSize = gridPlotMarkerSize;
gridPlotOptions.colors = gridPlotColors;
gridPlotOptions.lineStyles = gridPlotLineStyles;
gridPlotOptions.markers = gridPlotMarkers;
gridPlotOptions.referenceLineWidth = gridPlotReferenceLineWidth;
gridPlotOptions.referenceAnchor = gridPlotReferenceAnchor;
gridPlotOptions.referenceScale = gridPlotReferenceScale;
gridPlotOptions.referenceTrimLeftFraction = gridPlotReferenceTrimLeftFraction;
gridPlotOptions.referenceTrimRightFraction = gridPlotReferenceTrimRightFraction;
gridPlotOptions.titleText = gridPlotTitleText;
gridPlotOptions.xLabelText = gridPlotXLabelText;
gridPlotOptions.yLabelText = gridPlotYLabelText;
gridPlotOptions.titleFontSize = gridPlotTitleFontSize;
gridPlotOptions.axisLabelFontSize = gridPlotAxisLabelFontSize;
gridPlotOptions.tickFontSize = gridPlotTickFontSize;
gridPlotOptions.axesLineWidth = gridPlotAxesLineWidth;
gridPlotOptions.legendFontSize = gridPlotLegendFontSize;
gridPlotOptions.legendLocation = gridPlotLegendLocation;
gridPlotOptions.referenceStyle = gridPlotReferenceStyle;
gridPlotOptions.xScale = gridPlotXScale;
gridPlotOptions.yScale = gridPlotYScale;
gridPlotOptions.xLim = gridPlotXLim;
gridPlotOptions.yLim = gridPlotYLim;
gridPlotOptions.xTicks = gridPlotXTicks;
gridPlotOptions.yTicks = gridPlotYTicks;
gridPlotOptions.xTickLabels = gridPlotXTickLabels;
gridPlotOptions.yTickLabels = gridPlotYTickLabels;
gridPlotOptions.autoFormatXTicks = gridPlotAutoFormatXTicks;
gridPlotOptions.useDataXTicks = gridPlotUseDataXTicks;
gridPlotOptions.tickDir = gridPlotTickDir;
gridPlotOptions.tickLength = gridPlotTickLength;
gridPlotOptions.saveFig = gridPlotSaveFig;

% Output folder for postprocessed results.
postDir = fullfile(rootDir, 'postprocess_errors');
ensure_dir(postDir);

%% ===================== Load groups =====================

if ~exist(rootDir, 'dir')
    error('rootDir does not exist: %s', rootDir);
end

groups = load_result_groups(rootDir, GTagList, gammaList, CList, ...
    NList, tauList, dataReadMode);
if isempty(groups)
    error('No valid result group found under %s.', rootDir);
end

fprintf('Detected %d result group(s):\n', numel(groups));
for ig = 1:numel(groups)
    fprintf('  %2d: %s\n', ig, groups(ig).groupDir);
end

allTimeTables = cell(numel(groups), 1);
allScalarTables = cell(numel(groups), 1);
allSpatialTables = cell(numel(groups), 1);
allTemporalTables = cell(numel(groups), 1);

%% ===================== Main loop =====================

for ig = 1:numel(groups)
    group = groups(ig);
    results = group.results;
    valid = find_success_indices(results);
    if isempty(valid)
        warning('No successful results in group: %s', group.groupDir);
        continue;
    end
    results = results(valid);

    groupPostDir = make_group_post_dir(postDir, rootDir, group.groupDir);
    ensure_dir(groupPostDir);

    fprintf('\n============================================================\n');
    fprintf('Postprocessing group %d/%d\n', ig, numel(groups));
    fprintf('  folder: %s\n', group.groupDir);
    fprintf('  output: %s\n', groupPostDir);
    fprintf('============================================================\n');

    exactMode = use_exact_barenblatt(results(1));
    if exactMode
        fprintf('Reference mode for time histories: exact Barenblatt solution.\n');
        Rref = [];
        refIndex = NaN;
    else
        [Rref, refIndex] = choose_best_global_reference(results);
        fprintf('Reference mode for time histories: numerical reference.\n');
        fprintf('  N_ref = %d, h_ref = %.16g, tau_ref = %.6e\n', ...
            Rref.N, Rref.h, Rref.tau);
    end

    timeTable = compute_error_time_table(results, exactMode, Rref, refIndex, ...
        interpMethod, timeInterpMethod);
    scalarTable = reduce_error_time_table(timeTable, scalarErrorMode, ...
        targetTime, startTime, omitReferenceFromSummary);

    spatialTable = build_spatial_scalar_summary(results, exactMode, ...
        interpMethod, timeInterpMethod, scalarErrorMode, targetTime, startTime, ...
        omitReferenceFromSummary);
    temporalExactMode = exactMode;
    if strcmpi(temporalReferenceMode, 'numerical_same_N')
        temporalExactMode = false;
    elseif strcmpi(temporalReferenceMode, 'exact')
        temporalExactMode = exactMode;
    else
        error('Unknown temporalReferenceMode: %s.', temporalReferenceMode);
    end

    if temporalExactMode
        fprintf('Reference mode for temporal convergence: exact Barenblatt solution.\n');
    else
        fprintf('Reference mode for temporal convergence: numerical reference on the same N.\n');
    end

    temporalTable = build_temporal_scalar_summary(results, temporalExactMode, ...
        interpMethod, timeInterpMethod, scalarErrorMode, targetTime, startTime, ...
        omitReferenceFromSummary);

    allTimeTables{ig} = timeTable;
    allScalarTables{ig} = scalarTable;
    allSpatialTables{ig} = spatialTable;
    allTemporalTables{ig} = temporalTable;

    save(fullfile(groupPostDir, 'error_time_history.mat'), ...
        'timeTable', 'group', 'scalarErrorMode', 'targetTime', 'startTime', ...
        'temporalReferenceMode');
    write_table_compatible(timeTable, fullfile(groupPostDir, 'error_time_history.csv'));

    save(fullfile(groupPostDir, 'error_scalar_summary.mat'), ...
        'scalarTable', 'group', 'scalarErrorMode', 'targetTime', 'startTime', ...
        'temporalReferenceMode');
    save(fullfile(groupPostDir, 'error_spatial_summary.mat'), ...
        'spatialTable', 'group', 'scalarErrorMode', 'targetTime', 'startTime', ...
        'temporalReferenceMode');
    save(fullfile(groupPostDir, 'error_temporal_summary.mat'), ...
        'temporalTable', 'group', 'scalarErrorMode', 'targetTime', 'startTime', ...
        'temporalReferenceMode');
    write_table_compatible(scalarTable,  fullfile(groupPostDir, 'error_scalar_summary.csv'));
    write_table_compatible(spatialTable, fullfile(groupPostDir, 'error_spatial_summary.csv'));
    write_table_compatible(temporalTable, fullfile(groupPostDir, 'error_temporal_summary.csv'));

    fprintf('\nScalar summary for this group:\n');
    disp(scalarTable);
    fprintf('Spatial summary for this group:\n');
    disp(spatialTable);
    fprintf('Temporal summary for this group:\n');
    disp(temporalTable);

    if makePlots
        plot_error_time_history(timeTable, groupPostDir, plotLinf, ...
            plotReferenceZeroCurve, showTimeHistoryPlots);
    end
end

%% ===================== Combined outputs =====================

combinedTimeTable = vertcat_tables(allTimeTables);
combinedScalarTable = vertcat_tables(allScalarTables);
combinedSpatialTable = vertcat_tables(allSpatialTables);
combinedTemporalTable = vertcat_tables(allTemporalTables);

save(fullfile(postDir, 'combined_error_postprocess.mat'), ...
    'combinedTimeTable', 'combinedScalarTable', ...
    'combinedSpatialTable', 'combinedTemporalTable', ...
    'scalarErrorMode', 'targetTime', 'startTime', 'temporalReferenceMode');

save(fullfile(postDir, 'combined_error_time_history.mat'), ...
    'combinedTimeTable', 'scalarErrorMode', 'targetTime', 'startTime', ...
    'temporalReferenceMode');
save(fullfile(postDir, 'combined_error_scalar_summary.mat'), ...
    'combinedScalarTable', 'scalarErrorMode', 'targetTime', 'startTime', ...
    'temporalReferenceMode');
save(fullfile(postDir, 'combined_error_spatial_summary.mat'), ...
    'combinedSpatialTable', 'scalarErrorMode', 'targetTime', 'startTime', ...
    'temporalReferenceMode');
save(fullfile(postDir, 'combined_error_temporal_summary.mat'), ...
    'combinedTemporalTable', 'scalarErrorMode', 'targetTime', 'startTime', ...
    'temporalReferenceMode');

timeTable = combinedTimeTable;
scalarTable = combinedScalarTable;
spatialTable = combinedSpatialTable;
temporalTable = combinedTemporalTable;

save(fullfile(postDir, 'error_time_history.mat'), ...
    'timeTable', 'combinedTimeTable', 'scalarErrorMode', 'targetTime', 'startTime', ...
    'temporalReferenceMode');
save(fullfile(postDir, 'error_scalar_summary.mat'), ...
    'scalarTable', 'combinedScalarTable', 'scalarErrorMode', 'targetTime', 'startTime', ...
    'temporalReferenceMode');
save(fullfile(postDir, 'error_spatial_summary.mat'), ...
    'spatialTable', 'combinedSpatialTable', 'scalarErrorMode', 'targetTime', 'startTime', ...
    'temporalReferenceMode');
save(fullfile(postDir, 'error_temporal_summary.mat'), ...
    'temporalTable', 'combinedTemporalTable', 'scalarErrorMode', 'targetTime', 'startTime', ...
    'temporalReferenceMode');

write_table_compatible(combinedTimeTable,    fullfile(postDir, 'combined_error_time_history.csv'));
write_table_compatible(combinedScalarTable,  fullfile(postDir, 'combined_error_scalar_summary.csv'));
write_table_compatible(combinedSpatialTable, fullfile(postDir, 'combined_error_spatial_summary.csv'));
write_table_compatible(combinedTemporalTable, fullfile(postDir, 'combined_error_temporal_summary.csv'));
write_table_compatible(combinedTimeTable,    fullfile(postDir, 'error_time_history.csv'));
write_table_compatible(combinedScalarTable,  fullfile(postDir, 'error_scalar_summary.csv'));
write_table_compatible(combinedSpatialTable, fullfile(postDir, 'error_spatial_summary.csv'));
write_table_compatible(combinedTemporalTable, fullfile(postDir, 'error_temporal_summary.csv'));

if makePlots
    plot_error_time_history(combinedTimeTable, postDir, plotLinf, ...
        plotReferenceZeroCurve, showTimeHistoryPlots);
    if ~isempty(combinedTemporalTable) && height(combinedTemporalTable) > 0
        plot_error_vs_tau(combinedTemporalTable, postDir, showGridErrorPlots, ...
            startTime, showGridReferenceLine, gridReferenceSlope, gridPlotOptions);
    else
        warning('Temporal summary is empty. Falling back to error-vs-h plot.');
        fallbackPlotOptions = gridPlotOptions;
        fallbackPlotOptions.titleText = 'Spatial convergence error';
        fallbackPlotOptions.xLabelText = '$h$';
        plot_error_vs_h(combinedSpatialTable, postDir, showGridErrorPlots, ...
            startTime, showGridReferenceLine, gridReferenceSlope, fallbackPlotOptions);
    end
end

fprintf('\nPostprocessing finished. Combined outputs are in:\n  %s\n', postDir);

%% ========================================================================
%% Local functions
%% ========================================================================

function groups = load_result_groups(rootDir, GTagList, gammaList, CList, ...
    NList, tauList, dataReadMode)

    mode = lower(strtrim(dataReadMode));
    validModes = {'auto', 'all_case_results', 'case_result'};
    if ~any(strcmp(mode, validModes))
        error('Unknown dataReadMode: %s.', dataReadMode);
    end

    readAllCaseResults = ~strcmp(mode, 'case_result');
    readCaseResults = ~strcmp(mode, 'all_case_results');
    manualSelection = ~isempty(NList) || ~isempty(tauList);

    groups = struct('groupDir', {}, 'sourceFile', {}, 'results', {});
    loadedGroupDirs = {};

    if readAllCaseResults
        allFiles = find_files_recursive(rootDir, 'all_case_results.mat');
        for k = 1:numel(allFiles)
            filePath = allFiles{k};
            S = load(filePath);
            if ~isfield(S, 'results') || isempty(S.results)
                continue;
            end
            results = filter_results(S.results, GTagList, gammaList, CList, ...
                NList, tauList);
            if isempty(results)
                continue;
            end
            groups(end+1).groupDir = fileparts(filePath); %#ok<AGROW>
            groups(end).sourceFile = filePath;
            groups(end).results = results;
            loadedGroupDirs{end+1,1} = groups(end).groupDir; %#ok<AGROW>
        end
    end

    if ~readCaseResults
        return;
    end

    % Fallback: collect case_result.mat files for groups that do not have
    % all_case_results.mat.  When NList or tauList is set, also collect matching
    % case_result.mat files from groups that do have all_case_results.mat.
    caseFiles = find_files_recursive(rootDir, 'case_result.mat');
    if isempty(caseFiles)
        return;
    end

    groupDirs = cell(numel(caseFiles), 1);
    tmpResults = cell(numel(caseFiles), 1);
    keep = false(numel(caseFiles), 1);
    for k = 1:numel(caseFiles)
        S = load(caseFiles{k});
        if ~isfield(S, 'R') || isempty(S.R)
            continue;
        end
        R = S.R;
        if ~passes_result_filter(R, GTagList, gammaList, CList, NList, tauList)
            continue;
        end
        caseDir = fileparts(caseFiles{k});
        groupDir = fileparts(caseDir);
        if strcmp(mode, 'auto') && ~manualSelection && any(strcmp(groupDir, loadedGroupDirs))
            continue;
        end
        groupDirs{k} = groupDir;
        tmpResults{k} = R;
        keep(k) = true;
    end

    groupDirs = groupDirs(keep);
    tmpResults = tmpResults(keep);
    uniqueDirs = unique(groupDirs);
    for g = 1:numel(uniqueDirs)
        ids = strcmp(groupDirs, uniqueDirs{g});
        Rcell = tmpResults(ids);
        results = cell_to_struct_array(Rcell);
        groupId = find(strcmp({groups.groupDir}, uniqueDirs{g}), 1, 'first');
        if isempty(groupId)
            groups(end+1).groupDir = uniqueDirs{g}; %#ok<AGROW>
            groups(end).sourceFile = 'case_result.mat files';
            groups(end).results = results;
        else
            groups(groupId).sourceFile = [groups(groupId).sourceFile '; case_result.mat files'];
            groups(groupId).results = merge_results_unique(groups(groupId).results, results);
        end
    end
end

function results = filter_results(results, GTagList, gammaList, CList, NList, tauList)
    if isempty(results)
        return;
    end
    keep = false(size(results));
    for i = 1:numel(results)
        keep(i) = passes_result_filter(results(i), GTagList, gammaList, CList, ...
            NList, tauList);
    end
    results = results(keep);
end

function tf = passes_result_filter(R, GTagList, gammaList, CList, NList, tauList)
    tf = true;
    if ~isempty(GTagList)
        if ~isfield(R, 'G_tag') || ~any(strcmpi(R.G_tag, GTagList))
            tf = false;
            return;
        end
    end
    if ~isempty(gammaList)
        if ~isfield(R, 'gamma') || ~any(abs(R.gamma - gammaList) <= 1e-12)
            tf = false;
            return;
        end
    end
    if ~isempty(CList)
        if ~isfield(R, 'C') || ~any(abs(R.C - CList) <= 1e-12)
            tf = false;
            return;
        end
    end
    if ~isempty(NList)
        if ~isfield(R, 'N') || ~any(R.N == NList)
            tf = false;
            return;
        end
    end
    if ~isempty(tauList)
        if ~isfield(R, 'tau') || ~any(abs(R.tau - tauList) <= 1e-12 * max(1, abs(tauList)))
            tf = false;
            return;
        end
    end
end

function files = find_files_recursive(rootDir, targetName)
    files = {};
    D = dir(rootDir);
    for i = 1:numel(D)
        name = D(i).name;
        if strcmp(name, '.') || strcmp(name, '..')
            continue;
        end
        pathi = fullfile(rootDir, name);
        if D(i).isdir
            filesSub = find_files_recursive(pathi, targetName);
            files = [files; filesSub(:)]; %#ok<AGROW>
        else
            if strcmp(name, targetName)
                files{end+1,1} = pathi; %#ok<AGROW>
            end
        end
    end
end

function idx = find_success_indices(results)
    idx = [];
    for i = 1:numel(results)
        if isfield(results(i), 'success') && results(i).success
            if has_solution_snapshots(results(i))
                idx(end+1) = i; %#ok<AGROW>
            end
        end
    end
end

function tf = has_solution_snapshots(R)
    tf = isfield(R, 'snap_n') && ~isempty(R.snap_n) && ...
         isfield(R, 'x') && ~isempty(R.x);
    if ~tf && isfield(R, 'final_n') && ~isempty(R.final_n) && ...
            isfield(R, 'x') && ~isempty(R.x)
        tf = true;
    end
end

function tf = use_exact_barenblatt(R)
    tf = false;
    if isfield(R, 'exact_available') && R.exact_available
        tf = true;
        return;
    end
    if isfield(R, 'G_tag') && strcmpi(R.G_tag, 'G0')
        tf = true;
    end
end

function [Rref, refIndex] = choose_best_global_reference(results)
    h = zeros(numel(results), 1);
    tau = zeros(numel(results), 1);
    N = zeros(numel(results), 1);
    for i = 1:numel(results)
        h(i) = results(i).h;
        tau(i) = results(i).tau;
        N(i) = results(i).N;
    end
    A = [h, tau, -N];
    [~, perm] = sortrows(A, [1 2 3]);
    refIndex = perm(1);
    Rref = results(refIndex);
end

function timeTable = compute_error_time_table(results, exactMode, Rref, refIndex, ...
    interpMethod, timeInterpMethod)

    G_col = {};
    G_tag_col = {};
    gamma_col = [];
    C_col = [];
    N_col = [];
    h_col = [];
    tau_col = [];
    Nt_col = [];
    t_col = [];
    err_L1_col = [];
    err_Linf_col = [];
    ref_N_col = [];
    ref_h_col = [];
    ref_tau_col = [];
    is_ref_col = [];
    mode_col = {};

    for i = 1:numel(results)
        R = results(i);
        [snap_n, times] = get_snapshots_and_times(R);
        if isempty(snap_n)
            continue;
        end
        isRef = (~exactMode && i == refIndex);

        for j = 1:numel(times)
            t = times(j);
            nNum = snap_n(:, j);
            if exactMode
                nRef = barenblatt_exact(R.x, t, R.gamma, R.C, R.t0);
                refN = NaN;
                refh = NaN;
                reftau = NaN;
                modeText = 'exact Barenblatt';
            else
                nRef = evaluate_numerical_reference(Rref, t, R.x, interpMethod, timeInterpMethod);
                refN = Rref.N;
                refh = Rref.h;
                reftau = Rref.tau;
                modeText = sprintf('numerical reference: N=%d, tau=%.4g', Rref.N, Rref.tau);
            end

            diffj = nNum(:) - nRef(:);
            G_col{end+1,1} = get_string_field(R, 'G_label', ''); %#ok<AGROW>
            G_tag_col{end+1,1} = get_string_field(R, 'G_tag', ''); %#ok<AGROW>
            gamma_col(end+1,1) = R.gamma; %#ok<AGROW>
            C_col(end+1,1) = R.C; %#ok<AGROW>
            N_col(end+1,1) = R.N; %#ok<AGROW>
            h_col(end+1,1) = R.h; %#ok<AGROW>
            tau_col(end+1,1) = R.tau; %#ok<AGROW>
            Nt_col(end+1,1) = get_numeric_field(R, 'Nt', NaN); %#ok<AGROW>
            t_col(end+1,1) = t; %#ok<AGROW>
            err_L1_col(end+1,1) = R.h * sum(abs(diffj)); %#ok<AGROW>
            err_Linf_col(end+1,1) = max(abs(diffj)); %#ok<AGROW>
            ref_N_col(end+1,1) = refN; %#ok<AGROW>
            ref_h_col(end+1,1) = refh; %#ok<AGROW>
            ref_tau_col(end+1,1) = reftau; %#ok<AGROW>
            is_ref_col(end+1,1) = isRef; %#ok<AGROW>
            mode_col{end+1,1} = modeText; %#ok<AGROW>
        end
    end

    if isempty(t_col)
        timeTable = table();
        return;
    end

    timeTable = table(G_col, G_tag_col, gamma_col, C_col, N_col, h_col, ...
        tau_col, Nt_col, t_col, err_L1_col, err_Linf_col, ...
        ref_N_col, ref_h_col, ref_tau_col, is_ref_col, mode_col, ...
        'VariableNames', {'G','G_tag','gamma','C','N','h','tau','Nt','t', ...
        'err_L1','err_Linf','ref_N','ref_h','ref_tau','is_reference','error_mode'});
end

function scalarTable = reduce_error_time_table(timeTable, scalarErrorMode, ...
    targetTime, startTime, omitReference)

    if isempty(timeTable) || height(timeTable) == 0
        scalarTable = table();
        return;
    end

    keys = unique_case_keys(timeTable);

    G_col = {};
    G_tag_col = {};
    gamma_col = [];
    C_col = [];
    N_col = [];
    h_col = [];
    tau_col = [];
    err_L1_col = [];
    err_Linf_col = [];
    order_h_L1_col = [];
    order_tau_L1_col = [];
    scalar_time_col = [];
    num_times_col = [];
    ref_N_col = [];
    ref_h_col = [];
    ref_tau_col = [];
    is_ref_col = [];
    mode_col = {};

    for ik = 1:height(keys)
        idx = table_case_mask(timeTable, keys(ik,:));
        T = timeTable(idx,:);
        if omitReference && any(T.is_reference)
            continue;
        end
        [e1, einf, usedTime, nUsed] = reduce_one_error_curve(T.t, T.err_L1, T.err_Linf, ...
            scalarErrorMode, targetTime, startTime);

        G_col{end+1,1} = T.G{1}; %#ok<AGROW>
        G_tag_col{end+1,1} = T.G_tag{1}; %#ok<AGROW>
        gamma_col(end+1,1) = T.gamma(1); %#ok<AGROW>
        C_col(end+1,1) = T.C(1); %#ok<AGROW>
        N_col(end+1,1) = T.N(1); %#ok<AGROW>
        h_col(end+1,1) = T.h(1); %#ok<AGROW>
        tau_col(end+1,1) = T.tau(1); %#ok<AGROW>
        err_L1_col(end+1,1) = e1; %#ok<AGROW>
        err_Linf_col(end+1,1) = einf; %#ok<AGROW>
        order_h_L1_col(end+1,1) = NaN; %#ok<AGROW>
        order_tau_L1_col(end+1,1) = NaN; %#ok<AGROW>
        scalar_time_col(end+1,1) = usedTime; %#ok<AGROW>
        num_times_col(end+1,1) = nUsed; %#ok<AGROW>
        ref_N_col(end+1,1) = T.ref_N(1); %#ok<AGROW>
        ref_h_col(end+1,1) = T.ref_h(1); %#ok<AGROW>
        ref_tau_col(end+1,1) = T.ref_tau(1); %#ok<AGROW>
        is_ref_col(end+1,1) = T.is_reference(1); %#ok<AGROW>
        mode_col{end+1,1} = scalarErrorMode; %#ok<AGROW>
    end

    if isempty(err_L1_col)
        scalarTable = table();
        return;
    end

    scalarTable = table(G_col, G_tag_col, gamma_col, C_col, N_col, h_col, ...
        tau_col, err_L1_col, err_Linf_col, order_h_L1_col, order_tau_L1_col, ...
        scalar_time_col, num_times_col, ref_N_col, ref_h_col, ref_tau_col, ...
        is_ref_col, mode_col, ...
        'VariableNames', {'G','G_tag','gamma','C','N','h','tau','err_L1', ...
        'err_Linf','order_h_L1','order_tau_L1','scalar_time','num_times_used', ...
        'ref_N','ref_h','ref_tau','is_reference','scalar_error_mode'});

    scalarTable = add_orders_to_scalar_table(scalarTable);
end

function spatialTable = build_spatial_scalar_summary(results, exactMode, ...
    interpMethod, timeInterpMethod, scalarErrorMode, targetTime, startTime, omitReference)

    valid = 1:numel(results);
    tauVals = round_sig([results(valid).tau], 14);
    tauGroups = unique(tauVals);
    Tcell = cell(numel(tauGroups), 1);

    for g = 1:numel(tauGroups)
        ids = valid(tauVals == tauGroups(g));
        if numel(ids) < 2
            continue;
        end

        if exactMode
            ref = [];
            refIndexLocal = NaN;
        else
            [~, kref] = min([results(ids).h]);
            refIndexLocal = ids(kref);
            ref = results(refIndexLocal);
        end

        timeTable = compute_error_time_table(results(ids), exactMode, ref, ...
            local_ref_index(ids, refIndexLocal), interpMethod, timeInterpMethod);
        scalarTable = reduce_error_time_table(timeTable, scalarErrorMode, ...
            targetTime, startTime, omitReference);
        scalarTable = add_spatial_orders_only(scalarTable);
        Tcell{g} = scalarTable;
    end

    spatialTable = vertcat_tables(Tcell);
end

function temporalTable = build_temporal_scalar_summary(results, exactMode, ...
    interpMethod, timeInterpMethod, scalarErrorMode, targetTime, startTime, omitReference)

    valid = 1:numel(results);
    NVals = [results(valid).N];
    NGroups = unique(NVals);
    Tcell = cell(numel(NGroups), 1);

    for g = 1:numel(NGroups)
        ids = valid(NVals == NGroups(g));
        if numel(ids) < 2
            continue;
        end

        if exactMode
            ref = [];
            refIndexLocal = NaN;
        else
            [~, kref] = min([results(ids).tau]);
            refIndexLocal = ids(kref);
            ref = results(refIndexLocal);
        end

        timeTable = compute_error_time_table(results(ids), exactMode, ref, ...
            local_ref_index(ids, refIndexLocal), interpMethod, timeInterpMethod);
        scalarTable = reduce_error_time_table(timeTable, scalarErrorMode, ...
            targetTime, startTime, omitReference);
        scalarTable = add_temporal_orders_only(scalarTable);
        Tcell{g} = scalarTable;
    end

    temporalTable = vertcat_tables(Tcell);
end

function loc = local_ref_index(ids, globalId)
    if isnan(globalId)
        loc = NaN;
        return;
    end
    loc = find(ids == globalId, 1, 'first');
    if isempty(loc)
        loc = NaN;
    end
end

function [snap_n, times] = get_snapshots_and_times(R)
    if isfield(R, 'snap_n') && ~isempty(R.snap_n)
        snap_n = double(R.snap_n);
        if size(snap_n, 1) ~= numel(R.x) && size(snap_n, 2) == numel(R.x)
            snap_n = snap_n.';
        end
        if isfield(R, 'output_times') && ~isempty(R.output_times)
            times = R.output_times(:);
        else
            times = linspace(0, R.T, size(snap_n,2)).';
        end
        if numel(times) > size(snap_n,2)
            times = times(1:size(snap_n,2));
        elseif numel(times) < size(snap_n,2)
            snap_n = snap_n(:,1:numel(times));
        end
        return;
    end

    if isfield(R, 'final_n') && ~isempty(R.final_n)
        snap_n = R.final_n(:);
        times = R.T;
    else
        snap_n = [];
        times = [];
    end
end

function nRef = evaluate_numerical_reference(Rref, t, xQuery, interpMethod, timeInterpMethod)
    [snapRef, timesRef] = get_snapshots_and_times(Rref);
    if isempty(snapRef)
        error('Reference result has no snapshots or final solution.');
    end

    tol = 1e-10 * max(1, max(abs(timesRef)));
    [dmin, j] = min(abs(timesRef - t));
    if dmin <= tol
        nOnRefGrid = snapRef(:, j);
    else
        nOnRefGrid = interp1(timesRef(:), snapRef.', t, timeInterpMethod, 'extrap').';
    end

    if numel(xQuery) == numel(Rref.x) && max(abs(xQuery(:) - Rref.x(:))) <= 1e-12 * max(1, max(abs(Rref.x(:))))
        nRef = nOnRefGrid(:);
    else
        nRef = interp1(Rref.x(:), nOnRefGrid(:), xQuery(:), interpMethod, 'extrap');
        nRef = nRef(:);
    end
end

function [e1, einf, usedTime, nUsed] = reduce_one_error_curve(times, errL1, errLinf, ...
    scalarErrorMode, targetTime, startTime)

    times = times(:);
    errL1 = errL1(:);
    errLinf = errLinf(:);
    mode = lower(strtrim(scalarErrorMode));

    switch mode
        case {'at_time', 'time', 't'}
            if isempty(targetTime)
                target = max(times);
            else
                target = targetTime;
            end
            [~, j] = min(abs(times - target));
            e1 = errL1(j);
            einf = errLinf(j);
            usedTime = times(j);
            nUsed = 1;

        case {'mean_after', 'average_after', 'avg_after'}
            cutoffTol = 1e-14 * max(1, max(abs(times)));
            idx = times > startTime + cutoffTol;
            if ~any(idx)
                error('No saved time satisfies t > startTime = %.16g.', startTime);
            end
            e1 = mean(errL1(idx));
            einf = mean(errLinf(idx));
            usedTime = startTime;
            nUsed = sum(idx);

        case {'max_after', 'sup_after'}
            cutoffTol = 1e-14 * max(1, max(abs(times)));
            idx = times > startTime + cutoffTol;
            if ~any(idx)
                error('No saved time satisfies t > startTime = %.16g.', startTime);
            end
            e1 = max(errL1(idx));
            einf = max(errLinf(idx));
            usedTime = startTime;
            nUsed = sum(idx);

        otherwise
            error('Unknown scalarErrorMode: %s.', scalarErrorMode);
    end
end

function keys = unique_case_keys(T)
    A = table(T.G_tag, T.gamma, T.C, T.N, T.h, T.tau, ...
        'VariableNames', {'G_tag','gamma','C','N','h','tau'});
    keys = unique(A, 'rows');
end

function idx = table_case_mask(T, K)
    idx = strcmp(T.G_tag, K.G_tag{1}) & ...
        abs(T.gamma - K.gamma) <= 1e-12 & ...
        abs(T.C - K.C) <= 1e-12 & ...
        T.N == K.N & ...
        abs(T.h - K.h) <= 1e-12 * max(1, abs(K.h)) & ...
        abs(T.tau - K.tau) <= 1e-12 * max(1, abs(K.tau));
end

function T = add_orders_to_scalar_table(T)
    if isempty(T) || height(T) == 0
        return;
    end
    T = add_spatial_orders_only(T);
    T = add_temporal_orders_only(T);
end

function T = add_spatial_orders_only(T)
    if isempty(T) || height(T) == 0
        return;
    end
    T.order_h_L1(:) = NaN;
    Gtags = unique(T.G_tag);
    for ig = 1:numel(Gtags)
        idxG = strcmp(T.G_tag, Gtags{ig});
        gammas = unique(T.gamma(idxG)).';
        for a = gammas
            idxA = idxG & abs(T.gamma - a) <= 1e-12;
            Cs = unique(T.C(idxA)).';
            for c = Cs
                idxC = idxA & abs(T.C - c) <= 1e-12;
                taus = unique(round_sig(T.tau(idxC), 14)).';
                for tau0 = taus
                    idx = find(idxC & round_sig(T.tau, 14) == tau0);
                    if numel(idx) < 2
                        continue;
                    end
                    [~, perm] = sort(T.h(idx), 'descend');
                    idx = idx(perm);
                    ord = compute_orders(T.h(idx), T.err_L1(idx));
                    T.order_h_L1(idx) = ord;
                end
            end
        end
    end
end

function T = add_temporal_orders_only(T)
    if isempty(T) || height(T) == 0
        return;
    end
    T.order_tau_L1(:) = NaN;
    Gtags = unique(T.G_tag);
    for ig = 1:numel(Gtags)
        idxG = strcmp(T.G_tag, Gtags{ig});
        gammas = unique(T.gamma(idxG)).';
        for a = gammas
            idxA = idxG & abs(T.gamma - a) <= 1e-12;
            Cs = unique(T.C(idxA)).';
            for c = Cs
                idxC = idxA & abs(T.C - c) <= 1e-12;
                Ns = unique(T.N(idxC)).';
                for N0 = Ns
                    idx = find(idxC & T.N == N0);
                    if numel(idx) < 2
                        continue;
                    end
                    [~, perm] = sort(T.tau(idx), 'descend');
                    idx = idx(perm);
                    ord = compute_orders(T.tau(idx), T.err_L1(idx));
                    T.order_tau_L1(idx) = ord;
                end
            end
        end
    end
end

function orders = compute_orders(step, err)
    orders = NaN(size(err));
    for j = 2:numel(err)
        if err(j) > 0 && err(j-1) > 0 && step(j) > 0 && step(j-1) > 0
            orders(j) = log(err(j-1) / err(j)) / log(step(j-1) / step(j));
        end
    end
end

function plot_error_time_history(timeTable, outDir, plotLinf, plotReferenceZeroCurve, showPlots)
    if isempty(timeTable) || height(timeTable) == 0
        return;
    end

    make_one_error_time_plot(timeTable, outDir, 'L1', plotReferenceZeroCurve, showPlots);
    if plotLinf
        make_one_error_time_plot(timeTable, outDir, 'Linf', plotReferenceZeroCurve, showPlots);
    end
end

function make_one_error_time_plot(timeTable, outDir, normName, plotReferenceZeroCurve, showPlots)
    if strcmpi(normName, 'Linf')
        ylab = '$L^\infty$ error';
        fileName = 'error_vs_time_Linf.png';
    else
        ylab = '$L^1$ error';
        fileName = 'error_vs_time_L1.png';
    end

    visibleState = 'off';
    if showPlots
        visibleState = 'on';
    end

    fig = figure('Visible', visibleState, 'Color', 'w', ...
        'Name', fileName, 'NumberTitle', 'off');
    set(fig, 'Position', [100, 100, 900, 560]);
    hold on; box on; grid on;

    keys = unique_case_keys(timeTable);
    nPlotted = 0;
    for ik = 1:height(keys)
        idx = table_case_mask(timeTable, keys(ik,:));
        T = timeTable(idx,:);
        if any(T.is_reference) && ~plotReferenceZeroCurve
            continue;
        end
        [~, perm] = sort(T.t);
        T = T(perm,:);

        if strcmpi(normName, 'Linf')
            err = T.err_Linf;
        else
            err = T.err_L1;
        end

        errPlot = max(err, realmin);
        label = make_time_history_legend_label(T.G_tag{1}, T.gamma(1), ...
            T.N(1), T.h(1), T.tau(1));
        semilogy(T.t, errPlot, 'o-', 'LineWidth', 1.3, 'MarkerSize', 5, ...
            'DisplayName', label);
        nPlotted = nPlotted + 1;
    end

    if nPlotted == 0
        close(fig);
        return;
    end

    xlabel('$t$', 'Interpreter', 'latex');
    ylabel(ylab, 'Interpreter', 'latex');
    title('Error history', 'Interpreter', 'latex');
    legend('Location', 'bestoutside', 'Interpreter', 'latex');
    set(gca, 'FontSize', 13);
    print(fig, fullfile(outDir, fileName), '-dpng', '-r300');
    try
        savefig(fig, fullfile(outDir, strrep(fileName, '.png', '.fig')));
    catch
    end
    fprintf('  Wrote error history plot: %s\n', fullfile(outDir, fileName));
    if showPlots
        drawnow;
    else
        close(fig);
    end
end

function plot_error_vs_tau(temporalTable, outDir, showPlots, startTime, ...
    showReferenceLine, referenceSlope, plotOptions)
    if isempty(temporalTable) || height(temporalTable) == 0
        return;
    end

    fileName = 'error_vs_tau_L1.png';

    visibleState = 'off';
    if showPlots
        visibleState = 'on';
    end

    fig = figure('Visible', visibleState, 'Color', 'w', ...
        'Name', fileName, 'NumberTitle', 'off');
    set(fig, 'Position', plotOptions.figurePosition);
    ax = axes('Parent', fig);

    if isempty(plotOptions.xScale)
        plotOptions.xScale = 'log';
    end
    if isempty(plotOptions.yScale)
        plotOptions.yScale = 'log';
    end

    set(ax, 'XScale', plotOptions.xScale, 'YScale', plotOptions.yScale);
    hold(ax, 'on'); box(ax, 'on'); grid(ax, 'on');

    keys = unique(table(temporalTable.G_tag, temporalTable.gamma, ...
        temporalTable.C, temporalTable.N, ...
        'VariableNames', {'G_tag','gamma','C','N'}), 'rows');
    includeNInLegend = should_include_N_in_temporal_legend(keys);

    nPlotted = 0;
    allTau = [];
    allErr = [];
    colors = [];
    if isfield(plotOptions, 'colors')
        colors = plotOptions.colors;
    end
    lineStyles = plotOptions.lineStyles;
    markers = plotOptions.markers;
    if ischar(colors)
        colors = {colors};
    end
    if ischar(lineStyles)
        lineStyles = {lineStyles};
    end
    if ischar(markers)
        markers = {markers};
    end
    if isempty(lineStyles)
        lineStyles = {'-'};
    end
    if isempty(markers)
        markers = {'o'};
    end
    if isempty(colors)
        colors = [0.0000, 0.4470, 0.7410];
    end

    for ik = 1:height(keys)
        idx = strcmp(temporalTable.G_tag, keys.G_tag{ik}) & ...
            abs(temporalTable.gamma - keys.gamma(ik)) <= 1e-12 & ...
            abs(temporalTable.C - keys.C(ik)) <= 1e-12 & ...
            temporalTable.N == keys.N(ik);

        T = temporalTable(idx,:);
        valid = T.tau > 0 & T.err_L1 > 0;
        T = T(valid,:);
        if isempty(T) || height(T) == 0
            continue;
        end

        [~, perm] = sort(T.tau);
        T = T(perm,:);
        tauPlot = T.tau;

        if isnumeric(colors)
            thisColor = colors(1 + mod(nPlotted, size(colors, 1)), :);
        else
            thisColor = colors{1 + mod(nPlotted, numel(colors))};
        end
        thisLineStyle = lineStyles{1 + mod(nPlotted, numel(lineStyles))};
        thisMarker = markers{1 + mod(nPlotted, numel(markers))};

        label = make_temporal_legend_label(T.G_tag{1}, T.gamma(1), ...
            T.N(1), includeNInLegend);
        loglog(ax, tauPlot, T.err_L1, ...
            'Color', thisColor, ...
            'LineStyle', thisLineStyle, ...
            'Marker', thisMarker, ...
            'LineWidth', plotOptions.lineWidth, ...
            'MarkerSize', plotOptions.markerSize, ...
            'DisplayName', label);

        allTau = [allTau; tauPlot(:)]; %#ok<AGROW>
        allErr = [allErr; T.err_L1(:)]; %#ok<AGROW>
        nPlotted = nPlotted + 1;
    end

    if nPlotted == 0
        close(fig);
        return;
    end

    if showReferenceLine
        tauRefLine = unique(allTau(allTau > 0));
        if numel(tauRefLine) >= 2
            tauRefLine = sort(tauRefLine);
            tau_ref = tauRefLine(end);

            trimLeftFraction = 0;
            trimRightFraction = 0;
            if isfield(plotOptions, 'referenceTrimLeftFraction') && ...
                    ~isempty(plotOptions.referenceTrimLeftFraction)
                trimLeftFraction = plotOptions.referenceTrimLeftFraction;
            end
            if isfield(plotOptions, 'referenceTrimRightFraction') && ...
                    ~isempty(plotOptions.referenceTrimRightFraction)
                trimRightFraction = plotOptions.referenceTrimRightFraction;
            elseif isfield(plotOptions, 'referenceTrimFraction') && ...
                    ~isempty(plotOptions.referenceTrimFraction)
                trimRightFraction = plotOptions.referenceTrimFraction;
                trimLeftFraction = plotOptions.referenceTrimFraction;
            end
            trimLeftFraction = min(max(trimLeftFraction, 0), 0.45);
            trimRightFraction = min(max(trimRightFraction, 0), 0.45);

            tauLinePlot = tauRefLine;
            if (trimLeftFraction > 0 || trimRightFraction > 0) && ...
                    tauRefLine(1) > 0 && tauRefLine(end) > tauRefLine(1)
                logSpan = log(tauRefLine(end)) - log(tauRefLine(1));
                tauMinPlot = exp(log(tauRefLine(1)) + trimLeftFraction * logSpan);
                tauMaxPlot = exp(log(tauRefLine(end)) - trimRightFraction * logSpan);
                tauLinePlot = exp(linspace(log(tauMinPlot), log(tauMaxPlot), 50));
            end

            anchorTol = 1e-14 * max(1, abs(tau_ref));
            anchorIdx = abs(allTau - tau_ref) <= anchorTol & allErr > 0;
            if any(anchorIdx)
                anchorErr = allErr(anchorIdx);
                switch lower(plotOptions.referenceAnchor)
                    case 'max'
                        anchorValue = max(anchorErr);
                    case 'median'
                        anchorValue = median(anchorErr);
                    otherwise
                        anchorValue = min(anchorErr);
                end
                y_ref = plotOptions.referenceScale * anchorValue;
                refLine = y_ref * (tauLinePlot / tau_ref).^referenceSlope;
                refLabel = sprintf('slope $=%g$', referenceSlope);
                loglog(ax, tauLinePlot, refLine, plotOptions.referenceStyle, ...
                    'LineWidth', plotOptions.referenceLineWidth, ...
                    'DisplayName', refLabel);
            end
        end
    end

    xlabel(ax, plotOptions.xLabelText, ...
        'Interpreter', 'latex', ...
        'FontSize', plotOptions.axisLabelFontSize);
    ylabel(ax, plotOptions.yLabelText, ...
        'Interpreter', 'latex', ...
        'FontSize', plotOptions.axisLabelFontSize);
    title(ax, plotOptions.titleText, ...
        'Interpreter', 'latex', ...
        'FontSize', plotOptions.titleFontSize);
    legend(ax, 'Location', plotOptions.legendLocation, ...
        'Interpreter', 'latex', ...
        'FontSize', plotOptions.legendFontSize);
    set(ax, 'XScale', plotOptions.xScale, ...
        'YScale', plotOptions.yScale, ...
        'FontSize', plotOptions.tickFontSize, ...
        'LineWidth', plotOptions.axesLineWidth);

    tauVals = unique(temporalTable.tau(temporalTable.tau > 0));
    if ~isempty(plotOptions.xLim)
        set(ax, 'XLim', plotOptions.xLim);
    end
    if ~isempty(plotOptions.yLim)
        set(ax, 'YLim', plotOptions.yLim);
    end
    if ~isempty(plotOptions.xTicks)
        set(ax, 'XTick', plotOptions.xTicks);
    elseif plotOptions.useDataXTicks && numel(tauVals) <= 20
        set(ax, 'XTick', tauVals);
    end
    if ~isempty(plotOptions.yTicks)
        set(ax, 'YTick', plotOptions.yTicks);
    end
    if ~isempty(plotOptions.xTickLabels)
        set(ax, 'XTickLabel', plotOptions.xTickLabels);
    elseif isfield(plotOptions, 'autoFormatXTicks') && plotOptions.autoFormatXTicks
        set(ax, 'XTickLabel', format_log_tick_labels_latex(get(ax, 'XTick')));
    end
    if ~isempty(plotOptions.yTickLabels)
        set(ax, 'YTickLabel', plotOptions.yTickLabels);
    end
    set(ax, 'TickLabelInterpreter', 'latex', ...
        'TickDir', plotOptions.tickDir, ...
        'TickLength', plotOptions.tickLength);

    print(fig, fullfile(outDir, fileName), '-dpng', '-r300');
    if plotOptions.saveFig
        try
            savefig(fig, fullfile(outDir, strrep(fileName, '.png', '.fig')));
        catch
        end
    end
    fprintf('  Wrote temporal error plot: %s\n', fullfile(outDir, fileName));
    if showPlots
        figure(fig);
        drawnow;
    else
        close(fig);
    end
end

function plot_error_vs_h(spatialTable, outDir, showPlots, startTime, ...
    showReferenceLine, referenceSlope, plotOptions)
    if isempty(spatialTable) || height(spatialTable) == 0
        return;
    end

    fileName = 'error_vs_h_L1.png';

    visibleState = 'off';
    if showPlots
        visibleState = 'on';
    end

    fig = figure('Visible', visibleState, 'Color', 'w', ...
        'Name', fileName, 'NumberTitle', 'off');
    set(fig, 'Position', plotOptions.figurePosition);
    ax = axes('Parent', fig);

    if isempty(plotOptions.xScale)
        plotOptions.xScale = 'log';
    end
    if isempty(plotOptions.yScale)
        plotOptions.yScale = 'log';
    end

    set(ax, 'XScale', plotOptions.xScale, 'YScale', plotOptions.yScale);
    hold(ax, 'on'); box(ax, 'on'); grid(ax, 'on');

    keys = unique(table(spatialTable.G_tag, spatialTable.gamma, spatialTable.C, spatialTable.tau, ...
        'VariableNames', {'G_tag','gamma','C','tau'}), 'rows');
    includeTauInLegend = should_include_tau_in_grid_legend(keys);

    nPlotted = 0;
    allH = [];
    allErr = [];
    colors = [];
    if isfield(plotOptions, 'colors')
        colors = plotOptions.colors;
    end
    lineStyles = plotOptions.lineStyles;
    markers = plotOptions.markers;
    if ischar(colors)
        colors = {colors};
    end
    if ischar(lineStyles)
        lineStyles = {lineStyles};
    end
    if ischar(markers)
        markers = {markers};
    end
    if isempty(lineStyles)
        lineStyles = {'-'};
    end
    if isempty(markers)
        markers = {'o'};
    end
    if isempty(colors)
        colors = [0.0000, 0.4470, 0.7410];
    end
    for ik = 1:height(keys)
        idx = strcmp(spatialTable.G_tag, keys.G_tag{ik}) & ...
            abs(spatialTable.gamma - keys.gamma(ik)) <= 1e-12 & ...
            abs(spatialTable.C - keys.C(ik)) <= 1e-12 & ...
            abs(spatialTable.tau - keys.tau(ik)) <= 1e-12 * max(1, abs(keys.tau(ik)));

        T = spatialTable(idx,:);
        hPlot = compute_plot_h_from_N(T);
        valid = hPlot > 0 & T.err_L1 > 0;
        T = T(valid,:);
        hPlot = hPlot(valid);
        if isempty(T) || height(T) == 0
            continue;
        end

        [~, perm] = sort(hPlot);
        T = T(perm,:);
        hPlot = hPlot(perm);
        if isnumeric(colors)
            thisColor = colors(1 + mod(nPlotted, size(colors, 1)), :);
        else
            thisColor = colors{1 + mod(nPlotted, numel(colors))};
        end
        thisLineStyle = lineStyles{1 + mod(nPlotted, numel(lineStyles))};
        thisMarker = markers{1 + mod(nPlotted, numel(markers))};

        label = make_grid_legend_label(T.G_tag{1}, T.gamma(1), ...
            T.tau(1), includeTauInLegend);
        loglog(ax, hPlot, T.err_L1, ...
            'Color', thisColor, ...
            'LineStyle', thisLineStyle, ...
            'Marker', thisMarker, ...
            'LineWidth', plotOptions.lineWidth, ...
            'MarkerSize', plotOptions.markerSize, ...
            'DisplayName', label);
        allH = [allH; hPlot(:)]; %#ok<AGROW>
        allErr = [allErr; T.err_L1(:)]; %#ok<AGROW>
        nPlotted = nPlotted + 1;
    end

    if nPlotted == 0
        close(fig);
        return;
    end

    if showReferenceLine
        hrefLine = unique(allH(allH > 0));
        if numel(hrefLine) >= 2
            hrefLine = sort(hrefLine);
            h_ref = hrefLine(end);
            trimLeftFraction = 0;
            trimRightFraction = 0;
            if isfield(plotOptions, 'referenceTrimLeftFraction') && ...
                    ~isempty(plotOptions.referenceTrimLeftFraction)
                trimLeftFraction = plotOptions.referenceTrimLeftFraction;
            end
            if isfield(plotOptions, 'referenceTrimRightFraction') && ...
                    ~isempty(plotOptions.referenceTrimRightFraction)
                trimRightFraction = plotOptions.referenceTrimRightFraction;
            elseif isfield(plotOptions, 'referenceTrimFraction') && ...
                    ~isempty(plotOptions.referenceTrimFraction)
                trimRightFraction = plotOptions.referenceTrimFraction;
                trimLeftFraction = plotOptions.referenceTrimFraction;
            end
            trimLeftFraction = min(max(trimLeftFraction, 0), 0.45);
            trimRightFraction = min(max(trimRightFraction, 0), 0.45);
            hrefLinePlot = hrefLine;
            if (trimLeftFraction > 0 || trimRightFraction > 0) && ...
                    hrefLine(1) > 0 && hrefLine(end) > hrefLine(1)
                logSpan = log(hrefLine(end)) - log(hrefLine(1));
                hMinPlot = exp(log(hrefLine(1)) + trimLeftFraction * logSpan);
                hMaxPlot = exp(log(hrefLine(end)) - trimRightFraction * logSpan);
                hrefLinePlot = exp(linspace(log(hMinPlot), log(hMaxPlot), 50));
            end
            anchorTol = 1e-14 * max(1, abs(h_ref));
            anchorIdx = abs(allH - h_ref) <= anchorTol & allErr > 0;
            if any(anchorIdx)
                anchorErr = allErr(anchorIdx);
                switch lower(plotOptions.referenceAnchor)
                    case 'max'
                        anchorValue = max(anchorErr);
                    case 'median'
                        anchorValue = median(anchorErr);
                    otherwise
                        anchorValue = min(anchorErr);
                end
                y_ref = plotOptions.referenceScale * anchorValue;
                refLine = y_ref * (hrefLinePlot / h_ref).^referenceSlope;
                refLabel = sprintf('slope $=%g$', referenceSlope);
                loglog(ax, hrefLinePlot, refLine, plotOptions.referenceStyle, ...
                    'LineWidth', plotOptions.referenceLineWidth, ...
                    'DisplayName', refLabel);
            end
        end
    end

    xlabel(ax, plotOptions.xLabelText, ...
        'Interpreter', 'latex', ...
        'FontSize', plotOptions.axisLabelFontSize);
    ylabel(ax, plotOptions.yLabelText, ...
        'Interpreter', 'latex', ...
        'FontSize', plotOptions.axisLabelFontSize);
    title(ax, plotOptions.titleText, ...
        'Interpreter', 'latex', ...
        'FontSize', plotOptions.titleFontSize);
    legend(ax, 'Location', plotOptions.legendLocation, ...
        'Interpreter', 'latex', ...
        'FontSize', plotOptions.legendFontSize);
    set(ax, 'XScale', plotOptions.xScale, ...
        'YScale', plotOptions.yScale, ...
        'FontSize', plotOptions.tickFontSize, ...
        'LineWidth', plotOptions.axesLineWidth);

    Hvals = compute_plot_h_from_N(spatialTable);
    Hvals = unique(Hvals(Hvals > 0));
    if ~isempty(plotOptions.xLim)
        set(ax, 'XLim', plotOptions.xLim);
    end
    if ~isempty(plotOptions.yLim)
        set(ax, 'YLim', plotOptions.yLim);
    end
    if ~isempty(plotOptions.xTicks)
        set(ax, 'XTick', plotOptions.xTicks);
    elseif plotOptions.useDataXTicks && numel(Hvals) <= 20
        set(ax, 'XTick', Hvals);
    end
    if ~isempty(plotOptions.yTicks)
        set(ax, 'YTick', plotOptions.yTicks);
    end
    if ~isempty(plotOptions.xTickLabels)
        set(ax, 'XTickLabel', plotOptions.xTickLabels);
    elseif isfield(plotOptions, 'autoFormatXTicks') && plotOptions.autoFormatXTicks
        set(ax, 'XTickLabel', format_log_tick_labels_latex(get(ax, 'XTick')));
    end
    if ~isempty(plotOptions.yTickLabels)
        set(ax, 'YTickLabel', plotOptions.yTickLabels);
    end
    set(ax, 'TickLabelInterpreter', 'latex', ...
        'TickDir', plotOptions.tickDir, ...
        'TickLength', plotOptions.tickLength);

    print(fig, fullfile(outDir, fileName), '-dpng', '-r300');
    if plotOptions.saveFig
        try
            savefig(fig, fullfile(outDir, strrep(fileName, '.png', '.fig')));
        catch
        end
    end
    fprintf('  Wrote spatial error plot: %s\n', fullfile(outDir, fileName));

    if showPlots
        drawnow;
    else
        close(fig);
    end
end

function n = barenblatt_exact(x, t, gamma, C, t0)
    kappa = gamma / (gamma + 1.0);
    beta = 1.0 / (gamma + 2.0);
    s = kappa * (t + t0);
    if s <= 0
        error('Barenblatt parameter s must be positive.');
    end
    inside = C - (beta * gamma / (2.0 * (gamma + 1.0))) * (x(:).^2) / (s^(2.0 * beta));
    inside = max(inside, 0.0);
    n = s^(-beta) * inside.^(1.0 / gamma);
end

function T = vertcat_tables(Tcell)
    T = table();
    for i = 1:numel(Tcell)
        if ~isempty(Tcell{i}) && height(Tcell{i}) > 0
            if isempty(T)
                T = Tcell{i};
            else
                T = [T; Tcell{i}]; %#ok<AGROW>
            end
        end
    end
end

function arr = cell_to_struct_array(C)
    if isempty(C)
        arr = struct([]);
        return;
    end
    arr = C{1};
    for i = 2:numel(C)
        arr(i,1) = C{i}; %#ok<AGROW>
    end
end

function results = merge_results_unique(results, newResults)
    if isempty(results)
        results = newResults;
        return;
    end
    if isempty(newResults)
        return;
    end

    results = results(:);
    newResults = newResults(:);
    for i = 1:numel(newResults)
        if ~has_same_case(results, newResults(i))
            results(end+1,1) = newResults(i); %#ok<AGROW>
        end
    end
end

function tf = has_same_case(results, R)
    tf = false;
    for i = 1:numel(results)
        if strcmp(get_string_field(results(i), 'G_tag', ''), get_string_field(R, 'G_tag', '')) && ...
                nearly_equal(get_numeric_field(results(i), 'gamma', NaN), get_numeric_field(R, 'gamma', NaN)) && ...
                nearly_equal(get_numeric_field(results(i), 'C', NaN), get_numeric_field(R, 'C', NaN)) && ...
                get_numeric_field(results(i), 'N', NaN) == get_numeric_field(R, 'N', NaN) && ...
                nearly_equal(get_numeric_field(results(i), 'h', NaN), get_numeric_field(R, 'h', NaN)) && ...
                nearly_equal(get_numeric_field(results(i), 'tau', NaN), get_numeric_field(R, 'tau', NaN))
            tf = true;
            return;
        end
    end
end

function tf = nearly_equal(a, b)
    if isnan(a) || isnan(b)
        tf = false;
    else
        tf = abs(a - b) <= 1e-12 * max(1, max(abs([a, b])));
    end
end

function x = round_sig(x, ndig)
    scale = 10.^floor(log10(abs(x) + (x == 0)) - ndig + 1);
    x = round(x ./ scale) .* scale;
end

function label = make_grid_legend_label(Gtag, gammaValue, tauValue, includeTau)
    Glabel = growth_label_latex(Gtag);
    gammaLabel = gamma_value_latex(gammaValue);
    if includeTau
        label = sprintf('$\\gamma=%s,\\; %s,\\; \\tau=%.2g$', ...
            gammaLabel, Glabel, tauValue);
    else
        label = sprintf('$\\gamma=%s,\\; %s$', gammaLabel, Glabel);
    end
end

function label = make_temporal_legend_label(Gtag, gammaValue, NValue, includeN)
    Glabel = growth_label_latex(Gtag);
    gammaLabel = gamma_value_latex(gammaValue);
    if includeN
        label = sprintf('$\\gamma=%s,\\; %s,\\; N=%d$', ...
            gammaLabel, Glabel, NValue);
    else
        label = sprintf('$\\gamma=%s,\\; %s$', gammaLabel, Glabel);
    end
end

function hPlot = compute_plot_h_from_N(T)
    hPlot = T.h;
    validScale = T.N > 0 & T.h > 0 & isfinite(T.N) & isfinite(T.h);
    if any(validScale)
        domainLength = median(T.h(validScale) .* T.N(validScale));
        if isfinite(domainLength) && domainLength > 0
            hPlot = domainLength ./ T.N;
        end
    end
end

function label = make_time_history_legend_label(Gtag, gammaValue, NValue, hValue, tauValue)
    Glabel = growth_label_latex(Gtag);
    gammaLabel = gamma_value_latex(gammaValue);
    label = sprintf('$\\gamma=%s,\\; %s,\\; N=%d,\\ h=%.3g,\\ \\tau=%.2g$', ...
        gammaLabel, Glabel, NValue, hValue, tauValue);
end

function Glabel = growth_label_latex(Gtag)
    switch lower(strtrim(Gtag))
        case 'g0'
            Glabel = 'G(p)=0';
        case 'g1mp'
            Glabel = 'G(p)=1-p';
        otherwise
            Glabel = strrep(Gtag, '_', '\_');
    end
end

function gammaLabel = gamma_value_latex(gammaValue)
    gammaLabel = sprintf('%g', gammaValue);
    if gammaValue >= 0 && gammaValue < 10
        gammaLabel = sprintf('\\phantom{0}%g', gammaValue);
    end
end

function labels = format_log_tick_labels_latex(ticks)
    labels = cell(size(ticks));
    for i = 1:numel(ticks)
        x = ticks(i);
        if ~isfinite(x) || x <= 0
            labels{i} = '';
            continue;
        end

        exponent = floor(log10(x));
        mantissa = x / 10^exponent;
        mantissa = round(mantissa * 1e10) / 1e10;

        if abs(mantissa - 1) <= 1e-10
            labels{i} = sprintf('$10^{%d}$', exponent);
        else
            labels{i} = sprintf('$%g\\times 10^{%d}$', mantissa, exponent);
        end
    end
end

function tf = should_include_tau_in_grid_legend(keys)
    tf = false;
    for i = 1:height(keys)
        sameGrowthGamma = strcmp(keys.G_tag, keys.G_tag{i}) & ...
            abs(keys.gamma - keys.gamma(i)) <= 1e-12;
        if sum(sameGrowthGamma) > 1
            tf = true;
            return;
        end
    end
end

function tf = should_include_N_in_temporal_legend(keys)
    tf = false;
    for i = 1:height(keys)
        sameGrowthGamma = strcmp(keys.G_tag, keys.G_tag{i}) & ...
            abs(keys.gamma - keys.gamma(i)) <= 1e-12;
        if numel(unique(keys.N(sameGrowthGamma))) > 1
            tf = true;
            return;
        end
    end
end

function s = get_string_field(R, name, defaultValue)
    if isfield(R, name) && ~isempty(R.(name))
        s = R.(name);
    else
        s = defaultValue;
    end
end

function x = get_numeric_field(R, name, defaultValue)
    if isfield(R, name) && ~isempty(R.(name))
        x = R.(name);
    else
        x = defaultValue;
    end
end

function ensure_dir(folder)
    if ~exist(folder, 'dir')
        mkdir(folder);
    end
end

function groupPostDir = make_group_post_dir(postDir, rootDir, groupDir)
    rel = groupDir;
    rootPrefix = [rootDir filesep];
    if strncmp(groupDir, rootPrefix, numel(rootPrefix))
        rel = groupDir(numel(rootPrefix)+1:end);
    elseif strcmp(groupDir, rootDir)
        rel = 'root';
    end
    rel = strrep(rel, filesep, '__');
    rel = regexprep(rel, '[^\w\-.]', '_');
    if isempty(rel)
        rel = 'root';
    end
    groupPostDir = fullfile(postDir, rel);
end

function write_table_compatible(T, filename)
    if isempty(T)
        return;
    end
    try
        writetable(T, filename);
    catch
        warning('Could not write table with writetable: %s', filename);
    end
end
